##########################################################################################################
###### constraints file renux_top.xdc
##########################################################################################################


#//////////////////////////////////////////////////////////
#///// clock
#//////////////////////////////////////////////////////////
create_clock -period 5.000 -name clk [get_ports clk_p_i]


set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports clk_p_i]
set_property PACKAGE_PIN G18 [get_ports clk_n_i]
set_property PACKAGE_PIN H19 [get_ports clk_p_i]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports clk_n_i]
set_property PACKAGE_PIN AW40 [get_ports reset_i]
set_property IOSTANDARD LVCMOS18 [get_ports reset_i]


set_property MARK_DEBUG true [get_nets locked]
set_property MARK_DEBUG true [get_nets resetn]
set_property MARK_DEBUG true [get_nets {rdata[*]}]
set_property MARK_DEBUG true [get_nets sel]
set_property MARK_DEBUG true [get_nets {addr[*]}]
set_property MARK_DEBUG true [get_nets write]
set_property MARK_DEBUG true [get_nets {wdata[*]}]
set_property MARK_DEBUG true [get_nets scan_mode]

############################clock aysnc domain constrian###################################################
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ibufg_inst/O]
#
#set_false_path -from [get_ports reset_n_i]
#set_false_path -from [get_ports ahb_m_reset_n_i]
##set_false_path -from [get_pins PLLE3_BASE_inst/LOCKED]
#set_false_path -through [get_nets pll_locked]
#
#create_generated_clock -name axi_clk -source [get_pins BUFG_CLK_BUF_inst/I] -divide_by 1 [get_pins BUFG_CLK_BUF_inst/O]
#create_generated_clock -name ahb_clk -source [get_pins AHB_CLK_BUFG_inst/I] -divide_by 1 [get_pins AHB_CLK_BUFG_inst/O]
#
#set_max_delay -datapath_only -from [get_clocks axi_clk] -to [get_clocks ahb_clk] 40.000
#set_max_delay -datapath_only -from [get_clocks ahb_clk] -to [get_clocks axi_clk] 40.000
set_property DONT_TOUCH true [get_cells */*/*/RO_DLY*/*]
set_property DONT_TOUCH true [get_cells */*/*/RO_REF*/*]

#########
# trng0
set_property LOC SLICE_X110Y208 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y208 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X10Y205 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y208 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y208 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y208 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y208 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y207 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y207 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y207 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y207 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y207 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_0/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y206 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y206 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X120Y10 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y206 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y206 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y206 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y206 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y205 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y205 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y205 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y205 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y205 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_1/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y204 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y204 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X310Y94 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X110Y204 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y204 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y204 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y204 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y203 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y203 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y203 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y203 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y203 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_2/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y202 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y202 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X50Y40 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y202 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y202 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y202 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y202 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y201 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y201 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y201 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y201 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y201 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_DLY_3/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y200 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y200 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X245Y200 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X110Y200 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y200 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y200 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y200 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y199 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y199 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y199 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y199 [get_cells {dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y199 [get_cells dut/u_trng0/u_RO_ARRAY_REF/RO_REF/AA[10].DLY/LUT6_inst_del]

#########
# trng1

set_property LOC SLICE_X110Y198 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y198 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X189Y300 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y198 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y198 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y198 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y198 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y197 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y197 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y197 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y197 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y197 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_0/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y196 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y196 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X85Y300 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y196 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y196 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y196 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y196 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y195 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y195 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y195 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y195 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y195 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_1/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y194 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y194 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X30Y20 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y194 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y194 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y194 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y194 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y193 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y193 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y193 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y193 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y193 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_2/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y192 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y192 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X200Y100 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X110Y192 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y192 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y192 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y192 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y191 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y191 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y191 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y191 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y191 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_DLY_3/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X110Y190 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X110Y190 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X231Y130 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X110Y190 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y190 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y190 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y190 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y189 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y189 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y189 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y189 [get_cells {dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X110Y189 [get_cells dut/u_trng1/u_RO_ARRAY_REF/RO_REF/AA[10].DLY/LUT6_inst_del]

#########
# trng2
set_property LOC SLICE_X109Y208 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y208 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X100Y20 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y208 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y208 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y208 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y208 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y207 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y207 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y207 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y207 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y207 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_0/AA[10].DLY/LUT6_inst_del]

#set_property LOC SLICE_X109Y206 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[0].DLY/LUT6_inst_del]
set_property LOC SLICE_X222Y206 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[0].DLY/LUT6_inst_del]
set_property LOC SLICE_X109Y206 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y206 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y206 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y206 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y206 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y205 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y205 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y205 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y205 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y205 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_1/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y204 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y204 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X72Y204 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y204 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y204 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y204 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y204 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y203 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y203 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y203 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y203 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y203 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_2/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y202 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y202 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X125Y202 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y202 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y202 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y202 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y202 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y201 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y201 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y201 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y201 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y201 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_DLY_3/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y200 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y200 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X350Y10 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X109Y200 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y200 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y200 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y200 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y199 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y199 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y199 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y199 [get_cells {dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y199 [get_cells dut/u_trng2/u_RO_ARRAY_REF/RO_REF/AA[10].DLY/LUT6_inst_del]

#########
# trng3

set_property LOC SLICE_X109Y198 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y198 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X10Y85 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y198 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y198 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y198 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y198 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y197 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y197 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y197 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y197 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y197 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_0/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y196 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y196 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X30Y234 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y196 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y196 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y196 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y196 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y195 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y195 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y195 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y195 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y195 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_1/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y194 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y194 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X125Y194 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y194 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y194 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y194 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y194 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y193 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y193 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y193 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y193 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y193 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_2/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y192 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y192 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X234Y192 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X109Y192 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y192 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y192 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y192 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y191 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y191 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y191 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y191 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y191 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_DLY_3/AA[10].DLY/LUT6_inst_del]

set_property LOC SLICE_X109Y190 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[0].DLY/LUT6_inst_del}]
#set_property LOC SLICE_X109Y190 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del]
set_property LOC SLICE_X199Y10 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[1].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y190 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[2].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y190 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[3].DLY/LUT6_inst_del}]
set_property BEL D6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y190 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[4].DLY/LUT6_inst_del}]
set_property BEL C6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y190 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[5].DLY/LUT6_inst_del]
set_property BEL A6LUT [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y189 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[6].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y189 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[7].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y189 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[8].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y189 [get_cells {dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[9].DLY/LUT6_inst_del}]
set_property LOC SLICE_X109Y189 [get_cells dut/u_trng3/u_RO_ARRAY_REF/RO_REF/AA[10].DLY/LUT6_inst_del]





set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

###################################
##
###################################

set_false_path -from [get_clocks clk] -to [get_cells {*/*/u_trng_entity/count_samp_reg[*]}]
set_false_path -from [get_clocks clk] -to [get_cells */*/u_trng_entity/ro_samp_reg]
set_false_path -from [get_clocks clk] -to [get_cells */*/u_trng_entity/reset_samp_*]
#set_false_path -from [get_clocks CLK_100M_P] -to  u_trng1/u_RO_ARRAY_REF/ro_ref_out
#set_false_path -from [get_clocks CLK_100M_P] -to  u_trng2/u_RO_ARRAY_REF/ro_ref_out
#set_false_path -from [get_clocks CLK_100M_P] -to  u_trng3/u_RO_ARRAY_REF/ro_ref_out


#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_I_IBUF_inst/O]




#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets axi_s_aclk]










create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_xilinx_pll/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {addr[0]} {addr[1]} {addr[2]} {addr[3]} {addr[4]} {addr[5]} {addr[6]} {addr[7]} {addr[8]} {addr[9]} {addr[10]} {addr[11]} {addr[12]} {addr[13]} {addr[14]} {addr[15]} {addr[16]} {addr[17]} {addr[18]} {addr[19]} {addr[20]} {addr[21]} {addr[22]} {addr[23]} {addr[24]} {addr[25]} {addr[26]} {addr[27]} {addr[28]} {addr[29]} {addr[30]} {addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {rdata[0]} {rdata[1]} {rdata[2]} {rdata[3]} {rdata[4]} {rdata[5]} {rdata[6]} {rdata[7]} {rdata[8]} {rdata[9]} {rdata[10]} {rdata[11]} {rdata[12]} {rdata[13]} {rdata[14]} {rdata[15]} {rdata[16]} {rdata[17]} {rdata[18]} {rdata[19]} {rdata[20]} {rdata[21]} {rdata[22]} {rdata[23]} {rdata[24]} {rdata[25]} {rdata[26]} {rdata[27]} {rdata[28]} {rdata[29]} {rdata[30]} {rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ready[0]} {ready[1]} {ready[2]} {ready[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 80 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {result[0]} {result[1]} {result[2]} {result[3]} {result[4]} {result[5]} {result[6]} {result[7]} {result[8]} {result[9]} {result[10]} {result[11]} {result[12]} {result[13]} {result[14]} {result[15]} {result[16]} {result[17]} {result[18]} {result[19]} {result[20]} {result[21]} {result[22]} {result[23]} {result[24]} {result[25]} {result[26]} {result[27]} {result[28]} {result[29]} {result[30]} {result[31]} {result[32]} {result[33]} {result[34]} {result[35]} {result[36]} {result[37]} {result[38]} {result[39]} {result[40]} {result[41]} {result[42]} {result[43]} {result[44]} {result[45]} {result[46]} {result[47]} {result[48]} {result[49]} {result[50]} {result[51]} {result[52]} {result[53]} {result[54]} {result[55]} {result[56]} {result[57]} {result[58]} {result[59]} {result[60]} {result[61]} {result[62]} {result[63]} {result[64]} {result[65]} {result[66]} {result[67]} {result[68]} {result[69]} {result[70]} {result[71]} {result[72]} {result[73]} {result[74]} {result[75]} {result[76]} {result[77]} {result[78]} {result[79]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list resetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list write]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
